version: "3"

services:
  ########################################
  ############### Database ###############
  ########################################
  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    ports:
      - 5432:5432
    env_file: ./env/postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
